printshellcmds: true
keep-going: true
rerun-incomplete: true
latency-wait: 30
restart-times: 1
cores: 1
default-resources:
  mem_mb: 4096
  gpu: 1
use-conda: false
# 可选：详细日志
show-failed-logs: true
# DAG/报告类（需要时手动开启）
# report: true
