name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
      - name: Shellcheck (-x)
        run: |
          shopt -s globstar nullglob
          shellcheck -x -S error scripts/*.sh
      - name: Yaml lint (non-blocking)
        continue-on-error: true
        run: yamllint . || echo "yamllint found issues (non-blocking)"
      - name: Markdown lint
        continue-on-error: true
        run: |
          npx --yes markdownlint-cli@0.39.0 \
            -c .markdownlint.yml "**/*.md" \
            || echo "markdownlint found issues (non-blocking)"
      - name: Bash syntax check
        run: bash -n scripts/*.sh
      - name: Snakemake dry-run (non-blocking)
        continue-on-error: true
        run: |
          pipx install "snakemake>=9,<10" || pip install "snakemake>=9,<10"
          snakemake -s Snakefile --cores 1 -n || echo "snakemake dry-run skipped"
