---
name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          pipx install 'yamllint==1.35.1'
          npm i -g 'markdownlint-cli@0.42.0'
          sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Shellcheck (-x)
        run: |
          shopt -s globstar nullglob
          shellcheck -x -S error scripts/*.sh
      - name: Yaml lint
        run: yamllint -c .yamllint.yaml .
      - name: Markdown lint
        continue-on-error: true
        run: |
          markdownlint -c .markdownlint.yml "**/*.md" \
            || echo "markdownlint found issues (non-blocking)"
      - name: Bash syntax check
        run: bash -n scripts/*.sh
