name: CI
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          init-shell: bash
      - name: Create runner env
        shell: bash -l {0}
        run: |
          micromamba create -y -n runner -f envs/runner.yml
      - name: Snakemake dry-run
        shell: bash -l {0}
        run: |
          ./scripts/snk -s Snakefile -n --cores 1 --printshellcmds
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: ./scripts
      - name: Sanity (no GPU)
        shell: bash -l {0}
        run: |
          bash scripts/sanity_check.sh || true
