name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
      - name: Shellcheck (-x)
        run: |
          shopt -s globstar nullglob
          shellcheck -x -S warning scripts/*.sh
      - name: Yaml lint
        run: yamllint .
      - name: Markdown lint
        run: |
          npx --yes markdownlint-cli@0.39.0 \
            -c .markdownlint.yml "**/*.md"
      - name: Bash syntax check
        run: bash -n scripts/*.sh
