name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
          npm install -g markdownlint-cli
      - name: Shellcheck
        run: shellcheck scripts/*.sh
      - name: Yaml lint
        run: yamllint .
      - name: Markdown lint
        run: markdownlint '**/*.md'
      - name: Bash syntax check
        run: bash -n scripts/*.sh
