name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip/uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: ${{ runner.os }}-deps-${{ hashFiles('requirements-*.txt') }}

      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install ruff black shellcheck-py shfmt yamllint

      - name: Shellcheck (-x)
        run: |
          shopt -s globstar nullglob
          shellcheck -x -S error scripts/*.sh

      - name: Yaml lint (non-blocking)
        continue-on-error: true
        run: yamllint . || echo "yamllint found issues (non-blocking)"

      - name: Markdown lint
        continue-on-error: true
        run: |
          npx --yes markdownlint-cli@0.39.0 \
            -c .markdownlint.yml "**/*.md" \
            || echo "markdownlint found issues (non-blocking)"

      - name: Bash syntax check
        run: bash -n scripts/*.sh

      - name: Snakemake dry-run (non-blocking)
        continue-on-error: true
        run: |
          pipx install "snakemake>=9,<10" || pip install "snakemake>=9,<10"
          snakemake -s Snakefile --cores 1 -n --config slug=__ci__ || echo "snakemake dry-run skipped"
